### ISSUE TITLE
XML shortcuts not working in beta 111

### ISSUE THREAD

**Issue by ihaveamac** [mashers/3ds_hb_menu#34]
if a shortcut (usually for HANS) is selected, the launcher freezes instead of running the program.

beta 111; 2.5 payload date: 2015-11-09

[(originally from Flerp)](https://gbatemp.net/threads/release-homebrew-launcher-with-grid-layout.397527/page-168#post-5812950)

**Comment by giodude12** [comment]
Me tooooo.....

**Comment by mashers** [comment]
Ahh ok, it works if you launch the shortcut using the region 4 option in the boot menu instead of HANS. The problem is probably that booting the shortcut using the HANS option tries to boot HANS using HANS, which clearly won't work. I need to add some code to detect whether what's being booted is a title and if not, boot it as an app instead of using HANS.

**Comment by mashers** [comment]
Right, I think I've identified the issue and a fix but didn't have time to fully test ibeforehad to go to work. I'll be home in a couple of yours so a fix should be available very soon.

**Comment by mashers** [comment]
Just a progress update guys. I've got HANS shortcuts working fine, and am about to start on other (non-HANS) XML titles. Here's a table showing every permutation of launch type. I've tested all of these and will update the table as I progress with this bug.

Launch type | Auto HANS | Auto R4 | Manual HANS | Manual R4
----------- | --------- | ------- | ----------- | ---------
**Cart (main menu)** | OK | OK | OK | OK
**Cart (title menu)** | OK | OK | OK | OK
**Title (title menu)** | OK | OK | OK | OK
**Title (SVDT)** | OK | OK | N/A | N/A
**Homebrew app** | OK | OK | OK | OK
**HANS shortcut** | OK | OK | OK | OK
**XML Title** | NO | NO | NO | NO

**Comment by mashers** [comment]
Ok guys, please try with boot1.3dsx from this commit: https://github.com/mashers/3ds_hb_menu/commit/249db17912e1cd5f1194d82ebd42558c2c93d702

As you can see from the table above, everything should be working now. I'll wait to hear back from others before releasing another beta and closing this issue.

**Comment by mashers** [comment]
I haven't had any confirmation either way, but this definitely seems solved to me. I've released another beta update, so I'll close this issue now and if others are still having problems it can be reopened.

**Comment by ihaveamac** [comment]
XML shortcuts are working for me here.
On Nov 18, 2015, at 11:17 AM, mashers <notifications@github.com> wrote:

I haven't had any confirmation either way, but this definitely seems solved to me. I've released another beta update, so I'll close this issue now and if others are still having problems it can be reopened.
